// Code generated by ent, DO NOT EDIT.

package twapslicefill

import (
	"entgo.io/ent/dialect/sql"
	"github.com/yoshiso/hypersync/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldID, id))
}

// Coin applies equality check predicate on the "coin" field. It's identical to CoinEQ.
func Coin(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldCoin, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldAddress, v))
}

// Px applies equality check predicate on the "px" field. It's identical to PxEQ.
func Px(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldPx, v))
}

// Sz applies equality check predicate on the "sz" field. It's identical to SzEQ.
func Sz(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldSz, v))
}

// Side applies equality check predicate on the "side" field. It's identical to SideEQ.
func Side(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldSide, v))
}

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldTime, v))
}

// StartPosition applies equality check predicate on the "start_position" field. It's identical to StartPositionEQ.
func StartPosition(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldStartPosition, v))
}

// ClosedPnl applies equality check predicate on the "closed_pnl" field. It's identical to ClosedPnlEQ.
func ClosedPnl(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldClosedPnl, v))
}

// Dir applies equality check predicate on the "dir" field. It's identical to DirEQ.
func Dir(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldDir, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldHash, v))
}

// Crossed applies equality check predicate on the "crossed" field. It's identical to CrossedEQ.
func Crossed(v bool) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldCrossed, v))
}

// Fee applies equality check predicate on the "fee" field. It's identical to FeeEQ.
func Fee(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldFee, v))
}

// Oid applies equality check predicate on the "oid" field. It's identical to OidEQ.
func Oid(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldOid, v))
}

// Tid applies equality check predicate on the "tid" field. It's identical to TidEQ.
func Tid(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldTid, v))
}

// TwapID applies equality check predicate on the "twap_id" field. It's identical to TwapIDEQ.
func TwapID(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldTwapID, v))
}

// FeeToken applies equality check predicate on the "fee_token" field. It's identical to FeeTokenEQ.
func FeeToken(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldFeeToken, v))
}

// BuilderFee applies equality check predicate on the "builder_fee" field. It's identical to BuilderFeeEQ.
func BuilderFee(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldBuilderFee, v))
}

// CoinEQ applies the EQ predicate on the "coin" field.
func CoinEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldCoin, v))
}

// CoinNEQ applies the NEQ predicate on the "coin" field.
func CoinNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldCoin, v))
}

// CoinIn applies the In predicate on the "coin" field.
func CoinIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldCoin, vs...))
}

// CoinNotIn applies the NotIn predicate on the "coin" field.
func CoinNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldCoin, vs...))
}

// CoinGT applies the GT predicate on the "coin" field.
func CoinGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldCoin, v))
}

// CoinGTE applies the GTE predicate on the "coin" field.
func CoinGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldCoin, v))
}

// CoinLT applies the LT predicate on the "coin" field.
func CoinLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldCoin, v))
}

// CoinLTE applies the LTE predicate on the "coin" field.
func CoinLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldCoin, v))
}

// CoinContains applies the Contains predicate on the "coin" field.
func CoinContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldCoin, v))
}

// CoinHasPrefix applies the HasPrefix predicate on the "coin" field.
func CoinHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldCoin, v))
}

// CoinHasSuffix applies the HasSuffix predicate on the "coin" field.
func CoinHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldCoin, v))
}

// CoinEqualFold applies the EqualFold predicate on the "coin" field.
func CoinEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldCoin, v))
}

// CoinContainsFold applies the ContainsFold predicate on the "coin" field.
func CoinContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldCoin, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldAddress, v))
}

// PxEQ applies the EQ predicate on the "px" field.
func PxEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldPx, v))
}

// PxNEQ applies the NEQ predicate on the "px" field.
func PxNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldPx, v))
}

// PxIn applies the In predicate on the "px" field.
func PxIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldPx, vs...))
}

// PxNotIn applies the NotIn predicate on the "px" field.
func PxNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldPx, vs...))
}

// PxGT applies the GT predicate on the "px" field.
func PxGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldPx, v))
}

// PxGTE applies the GTE predicate on the "px" field.
func PxGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldPx, v))
}

// PxLT applies the LT predicate on the "px" field.
func PxLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldPx, v))
}

// PxLTE applies the LTE predicate on the "px" field.
func PxLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldPx, v))
}

// PxContains applies the Contains predicate on the "px" field.
func PxContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldPx, v))
}

// PxHasPrefix applies the HasPrefix predicate on the "px" field.
func PxHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldPx, v))
}

// PxHasSuffix applies the HasSuffix predicate on the "px" field.
func PxHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldPx, v))
}

// PxEqualFold applies the EqualFold predicate on the "px" field.
func PxEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldPx, v))
}

// PxContainsFold applies the ContainsFold predicate on the "px" field.
func PxContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldPx, v))
}

// SzEQ applies the EQ predicate on the "sz" field.
func SzEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldSz, v))
}

// SzNEQ applies the NEQ predicate on the "sz" field.
func SzNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldSz, v))
}

// SzIn applies the In predicate on the "sz" field.
func SzIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldSz, vs...))
}

// SzNotIn applies the NotIn predicate on the "sz" field.
func SzNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldSz, vs...))
}

// SzGT applies the GT predicate on the "sz" field.
func SzGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldSz, v))
}

// SzGTE applies the GTE predicate on the "sz" field.
func SzGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldSz, v))
}

// SzLT applies the LT predicate on the "sz" field.
func SzLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldSz, v))
}

// SzLTE applies the LTE predicate on the "sz" field.
func SzLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldSz, v))
}

// SzContains applies the Contains predicate on the "sz" field.
func SzContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldSz, v))
}

// SzHasPrefix applies the HasPrefix predicate on the "sz" field.
func SzHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldSz, v))
}

// SzHasSuffix applies the HasSuffix predicate on the "sz" field.
func SzHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldSz, v))
}

// SzEqualFold applies the EqualFold predicate on the "sz" field.
func SzEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldSz, v))
}

// SzContainsFold applies the ContainsFold predicate on the "sz" field.
func SzContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldSz, v))
}

// SideEQ applies the EQ predicate on the "side" field.
func SideEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldSide, v))
}

// SideNEQ applies the NEQ predicate on the "side" field.
func SideNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldSide, v))
}

// SideIn applies the In predicate on the "side" field.
func SideIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldSide, vs...))
}

// SideNotIn applies the NotIn predicate on the "side" field.
func SideNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldSide, vs...))
}

// SideGT applies the GT predicate on the "side" field.
func SideGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldSide, v))
}

// SideGTE applies the GTE predicate on the "side" field.
func SideGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldSide, v))
}

// SideLT applies the LT predicate on the "side" field.
func SideLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldSide, v))
}

// SideLTE applies the LTE predicate on the "side" field.
func SideLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldSide, v))
}

// SideContains applies the Contains predicate on the "side" field.
func SideContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldSide, v))
}

// SideHasPrefix applies the HasPrefix predicate on the "side" field.
func SideHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldSide, v))
}

// SideHasSuffix applies the HasSuffix predicate on the "side" field.
func SideHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldSide, v))
}

// SideEqualFold applies the EqualFold predicate on the "side" field.
func SideEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldSide, v))
}

// SideContainsFold applies the ContainsFold predicate on the "side" field.
func SideContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldSide, v))
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldTime, v))
}

// StartPositionEQ applies the EQ predicate on the "start_position" field.
func StartPositionEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldStartPosition, v))
}

// StartPositionNEQ applies the NEQ predicate on the "start_position" field.
func StartPositionNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldStartPosition, v))
}

// StartPositionIn applies the In predicate on the "start_position" field.
func StartPositionIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldStartPosition, vs...))
}

// StartPositionNotIn applies the NotIn predicate on the "start_position" field.
func StartPositionNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldStartPosition, vs...))
}

// StartPositionGT applies the GT predicate on the "start_position" field.
func StartPositionGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldStartPosition, v))
}

// StartPositionGTE applies the GTE predicate on the "start_position" field.
func StartPositionGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldStartPosition, v))
}

// StartPositionLT applies the LT predicate on the "start_position" field.
func StartPositionLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldStartPosition, v))
}

// StartPositionLTE applies the LTE predicate on the "start_position" field.
func StartPositionLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldStartPosition, v))
}

// StartPositionContains applies the Contains predicate on the "start_position" field.
func StartPositionContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldStartPosition, v))
}

// StartPositionHasPrefix applies the HasPrefix predicate on the "start_position" field.
func StartPositionHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldStartPosition, v))
}

// StartPositionHasSuffix applies the HasSuffix predicate on the "start_position" field.
func StartPositionHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldStartPosition, v))
}

// StartPositionEqualFold applies the EqualFold predicate on the "start_position" field.
func StartPositionEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldStartPosition, v))
}

// StartPositionContainsFold applies the ContainsFold predicate on the "start_position" field.
func StartPositionContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldStartPosition, v))
}

// ClosedPnlEQ applies the EQ predicate on the "closed_pnl" field.
func ClosedPnlEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldClosedPnl, v))
}

// ClosedPnlNEQ applies the NEQ predicate on the "closed_pnl" field.
func ClosedPnlNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldClosedPnl, v))
}

// ClosedPnlIn applies the In predicate on the "closed_pnl" field.
func ClosedPnlIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldClosedPnl, vs...))
}

// ClosedPnlNotIn applies the NotIn predicate on the "closed_pnl" field.
func ClosedPnlNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldClosedPnl, vs...))
}

// ClosedPnlGT applies the GT predicate on the "closed_pnl" field.
func ClosedPnlGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldClosedPnl, v))
}

// ClosedPnlGTE applies the GTE predicate on the "closed_pnl" field.
func ClosedPnlGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldClosedPnl, v))
}

// ClosedPnlLT applies the LT predicate on the "closed_pnl" field.
func ClosedPnlLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldClosedPnl, v))
}

// ClosedPnlLTE applies the LTE predicate on the "closed_pnl" field.
func ClosedPnlLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldClosedPnl, v))
}

// ClosedPnlContains applies the Contains predicate on the "closed_pnl" field.
func ClosedPnlContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldClosedPnl, v))
}

// ClosedPnlHasPrefix applies the HasPrefix predicate on the "closed_pnl" field.
func ClosedPnlHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldClosedPnl, v))
}

// ClosedPnlHasSuffix applies the HasSuffix predicate on the "closed_pnl" field.
func ClosedPnlHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldClosedPnl, v))
}

// ClosedPnlEqualFold applies the EqualFold predicate on the "closed_pnl" field.
func ClosedPnlEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldClosedPnl, v))
}

// ClosedPnlContainsFold applies the ContainsFold predicate on the "closed_pnl" field.
func ClosedPnlContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldClosedPnl, v))
}

// DirEQ applies the EQ predicate on the "dir" field.
func DirEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldDir, v))
}

// DirNEQ applies the NEQ predicate on the "dir" field.
func DirNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldDir, v))
}

// DirIn applies the In predicate on the "dir" field.
func DirIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldDir, vs...))
}

// DirNotIn applies the NotIn predicate on the "dir" field.
func DirNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldDir, vs...))
}

// DirGT applies the GT predicate on the "dir" field.
func DirGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldDir, v))
}

// DirGTE applies the GTE predicate on the "dir" field.
func DirGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldDir, v))
}

// DirLT applies the LT predicate on the "dir" field.
func DirLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldDir, v))
}

// DirLTE applies the LTE predicate on the "dir" field.
func DirLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldDir, v))
}

// DirContains applies the Contains predicate on the "dir" field.
func DirContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldDir, v))
}

// DirHasPrefix applies the HasPrefix predicate on the "dir" field.
func DirHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldDir, v))
}

// DirHasSuffix applies the HasSuffix predicate on the "dir" field.
func DirHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldDir, v))
}

// DirEqualFold applies the EqualFold predicate on the "dir" field.
func DirEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldDir, v))
}

// DirContainsFold applies the ContainsFold predicate on the "dir" field.
func DirContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldDir, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldHash, v))
}

// CrossedEQ applies the EQ predicate on the "crossed" field.
func CrossedEQ(v bool) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldCrossed, v))
}

// CrossedNEQ applies the NEQ predicate on the "crossed" field.
func CrossedNEQ(v bool) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldCrossed, v))
}

// FeeEQ applies the EQ predicate on the "fee" field.
func FeeEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldFee, v))
}

// FeeNEQ applies the NEQ predicate on the "fee" field.
func FeeNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldFee, v))
}

// FeeIn applies the In predicate on the "fee" field.
func FeeIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldFee, vs...))
}

// FeeNotIn applies the NotIn predicate on the "fee" field.
func FeeNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldFee, vs...))
}

// FeeGT applies the GT predicate on the "fee" field.
func FeeGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldFee, v))
}

// FeeGTE applies the GTE predicate on the "fee" field.
func FeeGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldFee, v))
}

// FeeLT applies the LT predicate on the "fee" field.
func FeeLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldFee, v))
}

// FeeLTE applies the LTE predicate on the "fee" field.
func FeeLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldFee, v))
}

// FeeContains applies the Contains predicate on the "fee" field.
func FeeContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldFee, v))
}

// FeeHasPrefix applies the HasPrefix predicate on the "fee" field.
func FeeHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldFee, v))
}

// FeeHasSuffix applies the HasSuffix predicate on the "fee" field.
func FeeHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldFee, v))
}

// FeeEqualFold applies the EqualFold predicate on the "fee" field.
func FeeEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldFee, v))
}

// FeeContainsFold applies the ContainsFold predicate on the "fee" field.
func FeeContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldFee, v))
}

// OidEQ applies the EQ predicate on the "oid" field.
func OidEQ(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldOid, v))
}

// OidNEQ applies the NEQ predicate on the "oid" field.
func OidNEQ(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldOid, v))
}

// OidIn applies the In predicate on the "oid" field.
func OidIn(vs ...int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldOid, vs...))
}

// OidNotIn applies the NotIn predicate on the "oid" field.
func OidNotIn(vs ...int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldOid, vs...))
}

// OidGT applies the GT predicate on the "oid" field.
func OidGT(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldOid, v))
}

// OidGTE applies the GTE predicate on the "oid" field.
func OidGTE(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldOid, v))
}

// OidLT applies the LT predicate on the "oid" field.
func OidLT(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldOid, v))
}

// OidLTE applies the LTE predicate on the "oid" field.
func OidLTE(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldOid, v))
}

// TidEQ applies the EQ predicate on the "tid" field.
func TidEQ(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldTid, v))
}

// TidNEQ applies the NEQ predicate on the "tid" field.
func TidNEQ(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldTid, v))
}

// TidIn applies the In predicate on the "tid" field.
func TidIn(vs ...int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldTid, vs...))
}

// TidNotIn applies the NotIn predicate on the "tid" field.
func TidNotIn(vs ...int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldTid, vs...))
}

// TidGT applies the GT predicate on the "tid" field.
func TidGT(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldTid, v))
}

// TidGTE applies the GTE predicate on the "tid" field.
func TidGTE(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldTid, v))
}

// TidLT applies the LT predicate on the "tid" field.
func TidLT(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldTid, v))
}

// TidLTE applies the LTE predicate on the "tid" field.
func TidLTE(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldTid, v))
}

// TwapIDEQ applies the EQ predicate on the "twap_id" field.
func TwapIDEQ(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldTwapID, v))
}

// TwapIDNEQ applies the NEQ predicate on the "twap_id" field.
func TwapIDNEQ(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldTwapID, v))
}

// TwapIDIn applies the In predicate on the "twap_id" field.
func TwapIDIn(vs ...int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldTwapID, vs...))
}

// TwapIDNotIn applies the NotIn predicate on the "twap_id" field.
func TwapIDNotIn(vs ...int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldTwapID, vs...))
}

// TwapIDGT applies the GT predicate on the "twap_id" field.
func TwapIDGT(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldTwapID, v))
}

// TwapIDGTE applies the GTE predicate on the "twap_id" field.
func TwapIDGTE(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldTwapID, v))
}

// TwapIDLT applies the LT predicate on the "twap_id" field.
func TwapIDLT(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldTwapID, v))
}

// TwapIDLTE applies the LTE predicate on the "twap_id" field.
func TwapIDLTE(v int64) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldTwapID, v))
}

// FeeTokenEQ applies the EQ predicate on the "fee_token" field.
func FeeTokenEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldFeeToken, v))
}

// FeeTokenNEQ applies the NEQ predicate on the "fee_token" field.
func FeeTokenNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldFeeToken, v))
}

// FeeTokenIn applies the In predicate on the "fee_token" field.
func FeeTokenIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldFeeToken, vs...))
}

// FeeTokenNotIn applies the NotIn predicate on the "fee_token" field.
func FeeTokenNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldFeeToken, vs...))
}

// FeeTokenGT applies the GT predicate on the "fee_token" field.
func FeeTokenGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldFeeToken, v))
}

// FeeTokenGTE applies the GTE predicate on the "fee_token" field.
func FeeTokenGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldFeeToken, v))
}

// FeeTokenLT applies the LT predicate on the "fee_token" field.
func FeeTokenLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldFeeToken, v))
}

// FeeTokenLTE applies the LTE predicate on the "fee_token" field.
func FeeTokenLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldFeeToken, v))
}

// FeeTokenContains applies the Contains predicate on the "fee_token" field.
func FeeTokenContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldFeeToken, v))
}

// FeeTokenHasPrefix applies the HasPrefix predicate on the "fee_token" field.
func FeeTokenHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldFeeToken, v))
}

// FeeTokenHasSuffix applies the HasSuffix predicate on the "fee_token" field.
func FeeTokenHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldFeeToken, v))
}

// FeeTokenEqualFold applies the EqualFold predicate on the "fee_token" field.
func FeeTokenEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldFeeToken, v))
}

// FeeTokenContainsFold applies the ContainsFold predicate on the "fee_token" field.
func FeeTokenContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldFeeToken, v))
}

// BuilderFeeEQ applies the EQ predicate on the "builder_fee" field.
func BuilderFeeEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEQ(FieldBuilderFee, v))
}

// BuilderFeeNEQ applies the NEQ predicate on the "builder_fee" field.
func BuilderFeeNEQ(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNEQ(FieldBuilderFee, v))
}

// BuilderFeeIn applies the In predicate on the "builder_fee" field.
func BuilderFeeIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIn(FieldBuilderFee, vs...))
}

// BuilderFeeNotIn applies the NotIn predicate on the "builder_fee" field.
func BuilderFeeNotIn(vs ...string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotIn(FieldBuilderFee, vs...))
}

// BuilderFeeGT applies the GT predicate on the "builder_fee" field.
func BuilderFeeGT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGT(FieldBuilderFee, v))
}

// BuilderFeeGTE applies the GTE predicate on the "builder_fee" field.
func BuilderFeeGTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldGTE(FieldBuilderFee, v))
}

// BuilderFeeLT applies the LT predicate on the "builder_fee" field.
func BuilderFeeLT(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLT(FieldBuilderFee, v))
}

// BuilderFeeLTE applies the LTE predicate on the "builder_fee" field.
func BuilderFeeLTE(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldLTE(FieldBuilderFee, v))
}

// BuilderFeeContains applies the Contains predicate on the "builder_fee" field.
func BuilderFeeContains(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContains(FieldBuilderFee, v))
}

// BuilderFeeHasPrefix applies the HasPrefix predicate on the "builder_fee" field.
func BuilderFeeHasPrefix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasPrefix(FieldBuilderFee, v))
}

// BuilderFeeHasSuffix applies the HasSuffix predicate on the "builder_fee" field.
func BuilderFeeHasSuffix(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldHasSuffix(FieldBuilderFee, v))
}

// BuilderFeeIsNil applies the IsNil predicate on the "builder_fee" field.
func BuilderFeeIsNil() predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldIsNull(FieldBuilderFee))
}

// BuilderFeeNotNil applies the NotNil predicate on the "builder_fee" field.
func BuilderFeeNotNil() predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldNotNull(FieldBuilderFee))
}

// BuilderFeeEqualFold applies the EqualFold predicate on the "builder_fee" field.
func BuilderFeeEqualFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldEqualFold(FieldBuilderFee, v))
}

// BuilderFeeContainsFold applies the ContainsFold predicate on the "builder_fee" field.
func BuilderFeeContainsFold(v string) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.FieldContainsFold(FieldBuilderFee, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TwapSliceFill) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TwapSliceFill) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TwapSliceFill) predicate.TwapSliceFill {
	return predicate.TwapSliceFill(sql.NotPredicates(p))
}
