// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yoshiso/hypersync/ent/delegatorreward"
	"github.com/yoshiso/hypersync/ent/predicate"
)

// DelegatorRewardDelete is the builder for deleting a DelegatorReward entity.
type DelegatorRewardDelete struct {
	config
	hooks    []Hook
	mutation *DelegatorRewardMutation
}

// Where appends a list predicates to the DelegatorRewardDelete builder.
func (drd *DelegatorRewardDelete) Where(ps ...predicate.DelegatorReward) *DelegatorRewardDelete {
	drd.mutation.Where(ps...)
	return drd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (drd *DelegatorRewardDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, drd.sqlExec, drd.mutation, drd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (drd *DelegatorRewardDelete) ExecX(ctx context.Context) int {
	n, err := drd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (drd *DelegatorRewardDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(delegatorreward.Table, sqlgraph.NewFieldSpec(delegatorreward.FieldID, field.TypeInt))
	if ps := drd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, drd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	drd.mutation.done = true
	return affected, err
}

// DelegatorRewardDeleteOne is the builder for deleting a single DelegatorReward entity.
type DelegatorRewardDeleteOne struct {
	drd *DelegatorRewardDelete
}

// Where appends a list predicates to the DelegatorRewardDelete builder.
func (drdo *DelegatorRewardDeleteOne) Where(ps ...predicate.DelegatorReward) *DelegatorRewardDeleteOne {
	drdo.drd.mutation.Where(ps...)
	return drdo
}

// Exec executes the deletion query.
func (drdo *DelegatorRewardDeleteOne) Exec(ctx context.Context) error {
	n, err := drdo.drd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{delegatorreward.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (drdo *DelegatorRewardDeleteOne) ExecX(ctx context.Context) {
	if err := drdo.Exec(ctx); err != nil {
		panic(err)
	}
}
