// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yoshiso/hypersync/ent/predicate"
	"github.com/yoshiso/hypersync/ent/spottransfer"
)

// SpotTransferQuery is the builder for querying SpotTransfer entities.
type SpotTransferQuery struct {
	config
	ctx        *QueryContext
	order      []spottransfer.OrderOption
	inters     []Interceptor
	predicates []predicate.SpotTransfer
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SpotTransferQuery builder.
func (stq *SpotTransferQuery) Where(ps ...predicate.SpotTransfer) *SpotTransferQuery {
	stq.predicates = append(stq.predicates, ps...)
	return stq
}

// Limit the number of records to be returned by this query.
func (stq *SpotTransferQuery) Limit(limit int) *SpotTransferQuery {
	stq.ctx.Limit = &limit
	return stq
}

// Offset to start from.
func (stq *SpotTransferQuery) Offset(offset int) *SpotTransferQuery {
	stq.ctx.Offset = &offset
	return stq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (stq *SpotTransferQuery) Unique(unique bool) *SpotTransferQuery {
	stq.ctx.Unique = &unique
	return stq
}

// Order specifies how the records should be ordered.
func (stq *SpotTransferQuery) Order(o ...spottransfer.OrderOption) *SpotTransferQuery {
	stq.order = append(stq.order, o...)
	return stq
}

// First returns the first SpotTransfer entity from the query.
// Returns a *NotFoundError when no SpotTransfer was found.
func (stq *SpotTransferQuery) First(ctx context.Context) (*SpotTransfer, error) {
	nodes, err := stq.Limit(1).All(setContextOp(ctx, stq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{spottransfer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (stq *SpotTransferQuery) FirstX(ctx context.Context) *SpotTransfer {
	node, err := stq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SpotTransfer ID from the query.
// Returns a *NotFoundError when no SpotTransfer ID was found.
func (stq *SpotTransferQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = stq.Limit(1).IDs(setContextOp(ctx, stq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{spottransfer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (stq *SpotTransferQuery) FirstIDX(ctx context.Context) int {
	id, err := stq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SpotTransfer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SpotTransfer entity is found.
// Returns a *NotFoundError when no SpotTransfer entities are found.
func (stq *SpotTransferQuery) Only(ctx context.Context) (*SpotTransfer, error) {
	nodes, err := stq.Limit(2).All(setContextOp(ctx, stq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{spottransfer.Label}
	default:
		return nil, &NotSingularError{spottransfer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (stq *SpotTransferQuery) OnlyX(ctx context.Context) *SpotTransfer {
	node, err := stq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SpotTransfer ID in the query.
// Returns a *NotSingularError when more than one SpotTransfer ID is found.
// Returns a *NotFoundError when no entities are found.
func (stq *SpotTransferQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = stq.Limit(2).IDs(setContextOp(ctx, stq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{spottransfer.Label}
	default:
		err = &NotSingularError{spottransfer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (stq *SpotTransferQuery) OnlyIDX(ctx context.Context) int {
	id, err := stq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SpotTransfers.
func (stq *SpotTransferQuery) All(ctx context.Context) ([]*SpotTransfer, error) {
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryAll)
	if err := stq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SpotTransfer, *SpotTransferQuery]()
	return withInterceptors[[]*SpotTransfer](ctx, stq, qr, stq.inters)
}

// AllX is like All, but panics if an error occurs.
func (stq *SpotTransferQuery) AllX(ctx context.Context) []*SpotTransfer {
	nodes, err := stq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SpotTransfer IDs.
func (stq *SpotTransferQuery) IDs(ctx context.Context) (ids []int, err error) {
	if stq.ctx.Unique == nil && stq.path != nil {
		stq.Unique(true)
	}
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryIDs)
	if err = stq.Select(spottransfer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (stq *SpotTransferQuery) IDsX(ctx context.Context) []int {
	ids, err := stq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (stq *SpotTransferQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryCount)
	if err := stq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, stq, querierCount[*SpotTransferQuery](), stq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (stq *SpotTransferQuery) CountX(ctx context.Context) int {
	count, err := stq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (stq *SpotTransferQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryExist)
	switch _, err := stq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (stq *SpotTransferQuery) ExistX(ctx context.Context) bool {
	exist, err := stq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SpotTransferQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (stq *SpotTransferQuery) Clone() *SpotTransferQuery {
	if stq == nil {
		return nil
	}
	return &SpotTransferQuery{
		config:     stq.config,
		ctx:        stq.ctx.Clone(),
		order:      append([]spottransfer.OrderOption{}, stq.order...),
		inters:     append([]Interceptor{}, stq.inters...),
		predicates: append([]predicate.SpotTransfer{}, stq.predicates...),
		// clone intermediate query.
		sql:  stq.sql.Clone(),
		path: stq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		User string `json:"user,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SpotTransfer.Query().
//		GroupBy(spottransfer.FieldUser).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (stq *SpotTransferQuery) GroupBy(field string, fields ...string) *SpotTransferGroupBy {
	stq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SpotTransferGroupBy{build: stq}
	grbuild.flds = &stq.ctx.Fields
	grbuild.label = spottransfer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		User string `json:"user,omitempty"`
//	}
//
//	client.SpotTransfer.Query().
//		Select(spottransfer.FieldUser).
//		Scan(ctx, &v)
func (stq *SpotTransferQuery) Select(fields ...string) *SpotTransferSelect {
	stq.ctx.Fields = append(stq.ctx.Fields, fields...)
	sbuild := &SpotTransferSelect{SpotTransferQuery: stq}
	sbuild.label = spottransfer.Label
	sbuild.flds, sbuild.scan = &stq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SpotTransferSelect configured with the given aggregations.
func (stq *SpotTransferQuery) Aggregate(fns ...AggregateFunc) *SpotTransferSelect {
	return stq.Select().Aggregate(fns...)
}

func (stq *SpotTransferQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range stq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, stq); err != nil {
				return err
			}
		}
	}
	for _, f := range stq.ctx.Fields {
		if !spottransfer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if stq.path != nil {
		prev, err := stq.path(ctx)
		if err != nil {
			return err
		}
		stq.sql = prev
	}
	return nil
}

func (stq *SpotTransferQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SpotTransfer, error) {
	var (
		nodes = []*SpotTransfer{}
		_spec = stq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SpotTransfer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SpotTransfer{config: stq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, stq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (stq *SpotTransferQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := stq.querySpec()
	_spec.Node.Columns = stq.ctx.Fields
	if len(stq.ctx.Fields) > 0 {
		_spec.Unique = stq.ctx.Unique != nil && *stq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, stq.driver, _spec)
}

func (stq *SpotTransferQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(spottransfer.Table, spottransfer.Columns, sqlgraph.NewFieldSpec(spottransfer.FieldID, field.TypeInt))
	_spec.From = stq.sql
	if unique := stq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if stq.path != nil {
		_spec.Unique = true
	}
	if fields := stq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, spottransfer.FieldID)
		for i := range fields {
			if fields[i] != spottransfer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := stq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := stq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := stq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := stq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (stq *SpotTransferQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(stq.driver.Dialect())
	t1 := builder.Table(spottransfer.Table)
	columns := stq.ctx.Fields
	if len(columns) == 0 {
		columns = spottransfer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if stq.sql != nil {
		selector = stq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if stq.ctx.Unique != nil && *stq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range stq.predicates {
		p(selector)
	}
	for _, p := range stq.order {
		p(selector)
	}
	if offset := stq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := stq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SpotTransferGroupBy is the group-by builder for SpotTransfer entities.
type SpotTransferGroupBy struct {
	selector
	build *SpotTransferQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (stgb *SpotTransferGroupBy) Aggregate(fns ...AggregateFunc) *SpotTransferGroupBy {
	stgb.fns = append(stgb.fns, fns...)
	return stgb
}

// Scan applies the selector query and scans the result into the given value.
func (stgb *SpotTransferGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, stgb.build.ctx, ent.OpQueryGroupBy)
	if err := stgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpotTransferQuery, *SpotTransferGroupBy](ctx, stgb.build, stgb, stgb.build.inters, v)
}

func (stgb *SpotTransferGroupBy) sqlScan(ctx context.Context, root *SpotTransferQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(stgb.fns))
	for _, fn := range stgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*stgb.flds)+len(stgb.fns))
		for _, f := range *stgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*stgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := stgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SpotTransferSelect is the builder for selecting fields of SpotTransfer entities.
type SpotTransferSelect struct {
	*SpotTransferQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sts *SpotTransferSelect) Aggregate(fns ...AggregateFunc) *SpotTransferSelect {
	sts.fns = append(sts.fns, fns...)
	return sts
}

// Scan applies the selector query and scans the result into the given value.
func (sts *SpotTransferSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sts.ctx, ent.OpQuerySelect)
	if err := sts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SpotTransferQuery, *SpotTransferSelect](ctx, sts.SpotTransferQuery, sts, sts.inters, v)
}

func (sts *SpotTransferSelect) sqlScan(ctx context.Context, root *SpotTransferQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sts.fns))
	for _, fn := range sts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
